apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-config
  namespace: default
data:
  billing.yaml: |
    db:
      master:
        host: patronidemo
        port: 5432
        user: postgres
        password: zalando
        name: billing
        sslmode: disable
      replica:
        host: patronidemo-repl
        port: 5432
        user: postgres
        password: zalando
        name: billing
        sslmode: disable
    brokers:
      - kafka-1:9094
    redisAddr: redis:6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
spec:
  selector:
    matchLabels:
      app: billing
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
        - name: billing
          image: gitlab-registry.ozon.dev/unknownspacewalker/homework3/billing:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /src/configs/
              readOnly: true
      imagePullSecrets:
        - name: regcred2
      volumes:
        - name: config
          configMap:
            name: billing-config
