apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
  namespace: default
data:
  notifications.yaml: |
    db:
      host: patronidemo
      port: 5432
      user: postgres
      password: zalando
      name: notifications
      sslmode: disable
    brokers:
      - kafka-1:9094
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
spec:
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - name: notifications
          image: gitlab-registry.ozon.dev/unknownspacewalker/homework3/notifications:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /src/configs/
              readOnly: true
      imagePullSecrets:
        - name: regcred2
      volumes:
        - name: config
          configMap:
            name: notifications-config
