apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-config
  namespace: default
data:
  orders.yaml: |
    db:
      host: patronidemo
      port: 5432
      user: postgres
      password: zalando
      name: orders
      sslmode: disable
    brokers:
      - kafka-1:9094
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
        - name: orders
          image: gitlab-registry.ozon.dev/unknownspacewalker/homework3/orders:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /src/configs/
              readOnly: true
      imagePullSecrets:
        - name: regcred2
      volumes:
        - name: config
          configMap:
            name: orders-config
