apiVersion: v1
kind: ConfigMap
metadata:
  name: stock-config
  namespace: default
data:
  stock.yaml: |
    db:
      host: patronidemo
      port: 5432
      user: postgres
      password: zalando
      name: stock
      sslmode: disable
    brokers:
      - kafka-1:9094
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock
spec:
  selector:
    matchLabels:
      app: stock
  template:
    metadata:
      labels:
        app: stock
    spec:
      containers:
        - name: stock
          image: gitlab-registry.ozon.dev/unknownspacewalker/homework3/stock:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /src/configs/
              readOnly: true
      imagePullSecrets:
        - name: regcred2
      volumes:
        - name: config
          configMap:
            name: stock-config
